name: CI test build

on:
  push:
      branches:
        - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101

    - name: Get current time
      uses: MyJetTools/get-current-time@v2
      id: current-time
      with:
        format: YYYY-MM-DD HH:mm:ss
        utcOffset: "+00:00"
        
    - name: Build
      run: dotnet build --configuration Release /p:AssemblyVersion=0.0.${{ github.run_number }}
    - name: Test
      run: dotnet test --no-build --configuration Release
    - name: ls
      run: ls

    - name: Publish Service
      run: dotnet publish --no-build ./src/Service.LkkPool/Service.LkkPool.csproj --configuration Release --output ./publish-api

    - name: Check Service dir
      run: ls ./publish-api
      
    - name: Publish image
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        path: ./publish-api
        registry: docker.pkg.github.com
        repository: ${{ secrets.ORG_NAME }}/service.lkkpool/myjetwallet.service.lkkpool-test
        tags: latest
        build_args: app_version=myjetwallet.service.lkkpool-test:latest,app_compilation_date=${{ steps.current-time.outputs.formattedTime }}

    - name: Publish image ST
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.ST_DOCKER_USER }}
        password: ${{ secrets.ST_DOCKER_PASSWORD }}
        path: ./publish-api
        registry: simpletrading.azurecr.io
        repository: spot/myjetwallet.service.lkkpool-test
        tags: latest
        add_git_labels: true
        build_args: app_version=myjetwallet.service.lkkpool-test:latest,app_compilation_date=${{ steps.current-time.outputs.formattedTime }}

  restart:
    runs-on: ubuntu-latest    
    needs: build
    steps:
    - name: Restart service
      uses: Myjetwallet/kube-restart-pods@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA__ST_TEST }}
        NAMESPACE: ${{ secrets.KUBE_TEST_NAMESPACE }}
        POD: lkkpool


